dist: jammy
language: php
php:
  - '8.2'
before_script: composer install; composer update; cd test
script: phpunit .
after_success:
  - "../trigger_travis_build.sh kiniauth"
env:
  global:
    secure: l+KQ83uwAnlAwfWs3J36+Bdrbe0Vz2CrF0smcUaY1i9F4gMi6TcoUxdSSIJ2CKxZalH60o0na7IYdjTRaEybS7a5DXv8+yuU0fZyjqpVRJqeTn4Y/PUzBnAaOgOwInSjCgVTYzmR5+I5gAlFA/B/YY8ZchTYrzz9CNKasEqHGFlld4nvjpJVNmKPJ6S6QHejsXUdsxuG7lnRSEA8TrTxmJJswV+PzHDbzfMeYblIOEppWcH2P1mPj8AgTK5U1WPGl3cX5/OrhgmCg278YMKXhum6u/ZP8tbEC/e6Vhx7Ur3jBrPmsgJeUh3fLpbr7SL4gduJLFR1KxorwMOEt7aYf9BmQI/5BS4onto0t6LxOmpbxj2m8SamNoQOH/qrWs/TWDaAjqrIOPK/Z+f5gzk07cmcMMS/TdMTYceSAD79mxVI7jU4JOzo7xbV5MHc2xSwuDKLHP4jwkv65t4VR1PIJ5A6XizVrnYIMHn9JfU+xaLa3f0gOiwHsgcrMTTOFiHxWlQRLYs8m1ewTa25oQYx5+MVmaq6PrVgfIpbNMVkEzvjSyJdhowm41mzn+JC7BG1Xq3Tmo9YYE1634mF/XEtkmqCxVLHLb3BUHlH7BQJAJ0ms9uEDbxlrCjpd8Zrr+soUYDO6u/6TxxfzjAeDd+zP4f1dTpx7oilHwv7/U1oRwQ=
notifications:
  slack:
    secure: M9s7/HRWarzbdDk2sCs5fY4kyamP75kQXUnOlyRp3LG+vbE4jVnzFYlXp8E2ucdW3tVZQvlh9J/iO7ktSLC7ooYAM19YvFjhjYPbYW6j/BBlPeK3HD47htHxfdvNxoYd4WjhOsukXUk8sBNAGln5Qh2HDlaccXMKqCe2Q6cw7B/g8YG9SSBwJcOOOiEQ3d6xg+mEnQEj4Djb5nLdAGKL+licP+QbsjGFwHRP5tC3E3RvdgbaCWc39jrghJzZ7GleHxP33sm0S8p6v58XiZPrLHMxnyMuzVYKlSADmklO8yM3nYm0zmn7hZfnZjkFIPW/zhz86KIx4UI6rkVTlQ4gz5ACG1tYCYJRu03r1TbSqRtTeM2C21CQkbB5mymmdbFKXKQmwE+2B0hzwdguuUAl5Pcjh3tPZ91QORWUT1UkkGhRvepmxd4wDQuV1upaPCaLUwYEXJISJYS3St8Ky+SAQPurqCSPnSUzfcFelqOOCsZFEiAopsqfJexD175/UgVH1lytKCucIjJ6qpTcdbDJcIrLQ6iWJCPrjQFdOTMJKZoKZR3uUbyXiHmNuUfZOVFGkVTxnZmZ3bqtp0wFRSjlHJEA7m9bzBtwxqcRAYTH1ldbBSVQZFnQnOSre4ZKyu+hVbIqx3iIPF8czmm/KHRE7NdNLWmafJgVN3zOoQvOrKw=
